# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "BURAYA_CLIENT_ID_GIR"
name = "ConvertFlow TR"
handle = "convertflow-tr"
application_url = "https://BURAYA_ADRES_GIR.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://BURAYA_ADRES_GIR.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/api/webhooks"

[app_proxy]
url = "https://BURAYA_ADRES_GIR.up.railway.app"
subpath = "convertflow"
prefix = "apps"

[pos]
embedded = false
